### ISSUE TITLE
Incompatable with latest KeePass v.2.39

### ISSUE THREAD

**Issue by nijel8** [betonme/kpenhancedlistview#9]
![capture](https://user-images.githubusercontent.com/1541030/39673983-3b88b272-5113-11e8-9b75-f5e3b6730b84.JPG)

Thank you!

**Comment by koddistortion** [comment]
The problem you are facing refers to the _KPEnhancedEntryView_ plugin, rather than the **KPEnhancedListView** plugin.

For the _KPEnhancedEntryView_ plugin a new version is available which is compatible with KeePass 2.39, see here https://sourceforge.net/projects/kpenhentryview/

**Comment by nijel8** [comment]
My bad, sorry...

**Comment by betonme** [comment]
Another plugin
